version = "3.11.1"
runner.dialect = scala213
maxColumn = 120
preset = default
rewrite.rules = [SortImports, RedundantParens, SortModifiers]
docstrings.style = Asterisk
# 全局匹配所有子模块产物
project.excludeFilters = ["**/target/", "**/generated/"]
