package com.huawei.omniruntime.flink.client;

import org.json.JSONObject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystem;
import java.nio.file.*;
import java.nio.file.attribute.BasicFileAttributes;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Enumeration;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import java.util.jar.JarEntry;
import java.util.jar.JarFile;
import java.util.stream.Stream;

public class NativeMain {
    private static final Logger LOG = LoggerFactory.getLogger(NativeMain.class);
    private static final int PORT = 8888;
    private static final String NATIVE_DIR = "native_dir";
    private static String hash = "";

    public static Properties getConfig(String jobJarPath) {
        try {
            LOG.debug("[Native] Received request: {}", jobJarPath);
            String prefix = System.getenv().getOrDefault("UDF_HOME", "/opt/udf-trans-opt/udf-translator");
            // Generate SO and configuration
            String scriptPath = "bash " + prefix + "/bin/udf_translate.sh "
                    + jobJarPath + " flink";
            hash = getFileHashCode(jobJarPath);
            String dest = System.getenv().getOrDefault("OMNI_LIBS", prefix + "/output/" + hash);
            boolean isAI4C = false;
            int code = 0;
            if (!System.getenv().containsKey("OMNI_LIBS")) {
                code = execute(scriptPath);
                // ai4c
                String cpp_path = prefix + "/cpp/" + hash;
                if (code == 0 && AI4C.isAi4c(cpp_path)) {
                   code = AI4C.activeAi4c(cpp_path);
                   if (code != 0) {
                       LOG.error("AI4C use failed!");
                       return new Properties();
                   } else {
                       isAI4C = true;
                       LOG.info("AI4C use success!");
                   }
                }
            } else {
                dest = System.getenv().get("OMNI_LIBS");
            }

            if (code == 0) {
                Path path = Paths.get(dest);
                Properties config = getConfigProperties(dest);
                rebuildJar(jobJarPath, path);
                if (isAI4C) {
                    config.setProperty("isAI4C", "true");
                }
                return config;
            } else {
                LOG.error("tar omni udf so failed");
                return new Properties();
            }
        } catch (Exception e) {
            LOG.error("Exception occurred while processing client request", e);
            return new Properties();
        }
    }

    public static int execute(String scriptPath) {
        try {
            Process process = Runtime.getRuntime().exec(scriptPath);
            // aovid the log generated by translation from occupying the cache and causing thread blocking.
            Thread outputThread = new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        LOG.debug("[STDOUT]" + line);
                    }
                } catch (IOException e) {
                    LOG.error("get InputStream Buffer Error", e);
                }
            });

            Thread errorThread = new Thread(() -> {
                try (BufferedReader reader = new BufferedReader(new InputStreamReader(process.getErrorStream(), StandardCharsets.UTF_8))) {
                    String line;
                    while ((line = reader.readLine()) != null) {
                        LOG.debug("[STDERR]" + line);
                    }
                } catch (IOException e) {
                    LOG.error("get ErrorStream Buffer Erro", e);
                }
            });

            outputThread.start();
            errorThread.start();
            return process.waitFor();
        } catch (Exception e) {
            LOG.error("Exception occurred while processing client request", e);
            return -1;
        }
    }

    private static Properties getConfigProperties(String dest) {
        Properties props = new Properties();

        try {
            // Build properties file path
            String propPath =  dest + "/udf.properties";
            try (FileInputStream fis = new FileInputStream(propPath)) {
                props.load(fis);
            }
        } catch (IOException e) {
            LOG.error("Properties file conversion failed", e);
        }

        return props;
    }

    // Repackage
    public static void rebuildJar(String jarPath, Path tempRootDir) throws IOException {
        Path nativeDir = null;

        try {
            // 1. Create native_dir directory
            nativeDir = createNativeDir(tempRootDir);
            // 2. Copy files in parallel
            copyFilesToNativeDir(tempRootDir, nativeDir);
            // 3. copy resource dir from jobJar to nativeDir
            copyResourceDirToNativeDir(jarPath, nativeDir);
            // 4. Update JAR
            updateJarFile(jarPath, nativeDir);
        } finally {
            // Clean up temporary folder
            if (nativeDir != null) {
                cleanTempDir(nativeDir);
            }
        }
    }

    // Create native_dir directory
    private static Path createNativeDir(Path tempDir) throws IOException {
        Path nativeDir = tempDir.resolve(NATIVE_DIR);
        Files.createDirectories(nativeDir);
        return nativeDir;
    }

    // Parallel file copying
    private static void copyFilesToNativeDir(Path sourceDir, Path targetDir) throws IOException {
        // Create target directory
        Files.createDirectories(targetDir);

        try (Stream<Path> pathStream = Files.list(sourceDir)) {
            pathStream.parallel()
                    .filter(path -> {
                        // Precisely filter directories and self paths
                        return !Files.isDirectory(path) &&
                                !path.toAbsolutePath().equals(targetDir.toAbsolutePath());
                    })
                    .forEach(path -> {
                        // Generate unique target path
                        Path dest = targetDir.resolve(sourceDir.relativize(path));
                        try {
                            Files.copy(path, dest,
                                    StandardCopyOption.REPLACE_EXISTING,
                                    StandardCopyOption.COPY_ATTRIBUTES);
                        } catch (FileAlreadyExistsException e) {
                            LOG.warn("File already exists, automatically skipped: {}", dest);
                        } catch (IOException e) {
                            throw new UncheckedIOException(
                                    "File copy failed [" + path + " → " + dest + "]", e);
                        }
                    });
        }
    }

    private static void copyResourceDirToNativeDir(String jarPath, Path nativeDir) throws IOException {
        Files.createDirectories(nativeDir);

        try (JarFile jar = new JarFile(jarPath)) {
            Enumeration<JarEntry> entries = jar.entries();
            while (entries.hasMoreElements()) {
                JarEntry entry = entries.nextElement();
                // Check if it's a file in root directory: not a directory and path contains no subdirectories
                String entryName = entry.getName();
                if (!entry.isDirectory() && !entryName.contains("/") && !entryName.contains("\\")) {
                    Path targetFile = nativeDir.resolve(entry.getName());
                    // Use try-with-resources to ensure stream closure
                    try (InputStream is = jar.getInputStream(entry);
                         OutputStream os = Files.newOutputStream(targetFile)) {
                        // Use buffer to copy file content
                        byte[] buffer = new byte[4096];
                        int bytesRead;
                        while ((bytesRead = is.read(buffer)) != -1) {
                            os.write(buffer, 0, bytesRead);
                        }
                    }
                }
            }
        }
    }

    // Update JAR file
    private static void updateJarFile(String jarPath, Path nativeDir) throws IOException {
        Path jarFile = Paths.get(jarPath);
        URI jarUri = URI.create("jar:" + jarFile.toUri());  // Construct JAR protocol URI

        // Environment variable settings
        Map<String, String> env = new HashMap<>();
        env.put("create", "true");  // Allow creating new entries
        env.put("encoding", "UTF-8");  // Specify character set

        try (FileSystem fs = FileSystems.newFileSystem(jarUri, env)) {
            Files.walk(nativeDir)
                    .filter(path -> !Files.isDirectory(path))
                    .parallel()  // Parallel processing improves efficiency
                    .forEach(path -> {
                        // Generate JAR internal path
                        String entryName = NATIVE_DIR + "/" +
                                nativeDir.relativize(path).toString().replace(File.separator, "/");

                        try {
                            Path dest = fs.getPath(entryName);
                            Files.createDirectories(dest.getParent());  // Create parent directory

                            // Memory mapping accelerates writing
                            try (InputStream in = new BufferedInputStream(Files.newInputStream(path));
                                OutputStream out = new BufferedOutputStream(
                                    Files.newOutputStream(dest,
                                        StandardOpenOption.CREATE,
                                        StandardOpenOption.TRUNCATE_EXISTING))) {

                                byte[] buffer = new byte[8192];  // 8KB buffer reduces IO operations
                                int bytesRead;
                                while ((bytesRead = in.read(buffer)) != -1) {
                                    out.write(buffer, 0, bytesRead);
                                }
                            }
                        } catch (FileAlreadyExistsException e) {
                            LOG.warn("File conflict automatically skipped: {}", entryName);  // Concurrent write protection
                        } catch (IOException e) {
                            throw new UncheckedIOException("JAR entry write failed: " + entryName, e);
                        }
                    });
        } catch (FileSystemAlreadyExistsException e) {
            // Handle duplicate file system loading
            try (FileSystem fs = FileSystems.getFileSystem(jarUri)) {
                LOG.debug("Reuse already loaded JAR file system");
            }
        }
    }

    // Clean up temporary folder
    private static void cleanTempDir(Path outputDir) throws IOException {
        if (!Files.exists(outputDir)) {
            return;
        }

        Files.walkFileTree(outputDir, new SimpleFileVisitor<Path>() {
            @Override
            public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
                // Force delete occupied files
                if (!file.toFile().delete()) {
                    Files.delete(file); // NIO second attempt
                }
                return FileVisitResult.CONTINUE;
            }

            @Override
            public FileVisitResult postVisitDirectory(Path dir, IOException exc) throws IOException {
                // Delete directory last
                Files.delete(dir);
                return FileVisitResult.CONTINUE;
            }
        });
    }

    // Convert properties file to JSON
    private static JSONObject convertPropToJson(String jarPath) {
        JSONObject result = new JSONObject(true); // Maintain order

        try {
            // Get jar file directory path
            File jarFile = new File(jarPath);
            String parentDir = jarFile.getParent();

            // Build properties file path
            String propPath = parentDir + File.separator + "udf-translator" + File.separator
                    + "output" + File.separator + hash + File.separator + "udf.properties";

            // Read properties file
            Properties props = new Properties();
            try (FileInputStream fis = new FileInputStream(propPath)) {
                props.load(fis);

                // Convert to JSON object
                props.forEach((k, v) ->
                        result.put(k.toString(), v.toString())
                );
            }
        } catch (IOException e) {
            LOG.error("Properties file conversion failed", e);
        }

        return result;
    }

    // Get hash value based on jar content
    public static String getFileHashCode(String jarFilePath) throws IOException, NoSuchAlgorithmException {
        MessageDigest digest = MessageDigest.getInstance("SHA-256");
        try (FileInputStream fis = new FileInputStream(jarFilePath)) {
            byte[] byteArray = new byte[1024];
            int byteCount;
            while ((byteCount = fis.read(byteArray)) != -1) {
                digest.update(byteArray,0,byteCount);
            }
        }
        byte[] bytes = digest.digest();
        StringBuilder sb = new StringBuilder();
        for (byte b : bytes) {
            String hex = Integer.toHexString(0xff & b);
            if (hex.length() == 1) {
                sb.append("0");
            }
            sb.append(hex);
        }
        return sb.toString();
    }
}
